
[grpc]
grpc_addr = ":9003"          # grpc server地址
grpc_handler_timeout = 5000  # grpc Handler timeout(ms), default 5000

[log]
filename = "log/recorder.log.%Y%m%d%H"
linkname = "log/recorder.log"
maxHourAge    = 4 # 默认日志保留4小时
maxHourRotate = 1 # 默认日志按小时切分